[package]
name = "rekernel"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rekernel_headers = { path = "../headers" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
