[package]
name = "x86-linux-rs"
version = "0.1.0"
description = "linux-rs (experimental rewrite) x86 arch specific code"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[profile.test]
panic = "abort"

