[package]
name = "x86_linux_rs"
version = "0.1.0"
description = "linux-rs (experimental rewrite) x86 arch specific code"
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[profile.test]
panic = "abort"

[dependencies]
linux_rs = { path = "../../kernel" }
