[package]
name = "unified_os_boot"         # or any other name
version = "0.1.0"

[build-dependencies]
bootloader = "0.11.3"
unified_os = { path = "kernel", artifact = "bin", target = "target.json"}

[dependencies]
# used for UEFI booting in QEMU
ovmf-prebuilt = "0.1.0-alpha.1"
