name: Build kernel with actions

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Python
      uses: actions/setup-python@v4.7.0
      with:
        python-version: 3.11
        architecture: x64
    - name: Make dir for output
      run: mkdir /tmp/output
    - uses: actions/checkout@v3
    - name: Build with Python on debug (legacy)
      run: python3 build.py --debug --nodebugconsole --norun
    - name: Move debug artifact
      run: mv build/kernel/target/target/debug/bootimage-rekernel.bin /tmp/output/legacy_image-debug.bin 
    - name: Build with Python on release (legacy)
      run: python3 build.py --norun
    - name: Move release artifact
      run: mv build/kernel/target/target/release/bootimage-rekernel.bin /tmp/output/legacy_image-release.bin 
    - name: Move logs
      run: mv logs /tmp/output/legacy_logs
    # - name: Clean env
    #   run: python3 build.py clean NOTE no more need
    - name: Build with Python on debug (image)
      run: python3 build.py --debug --nodebugconsole --norun image
    - name: Move artifacts
      run: mkdir /tmp/output/image-debug && mv build/image/target/*-linux-gnu/debug/build/rekernel_image-*/out/*.img /tmp/output/image-debug
    - name: Build with Python on release (image)
      run: python3 build.py --norun image
    - name: Move artifacts
      run: mkdir /tmp/output/image-release && mv build/image/target/*-linux-gnu/release/build/rekernel_image-*/out/*.img /tmp/output/image-release
    - name: Tarballing artifacts
      run: tar cJf /tmp/output.tar.xz /tmp/output
    - name: Uploading data
      uses: actions/upload-artifact@v3.1.2
      with:
        name: build-data.tar.xz
        path: /tmp/output.tar.xz
        if-no-files-found: error
        retention-days: 30
    
